name: Build and Push Driver Image for Preview

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Build driver binary
        run: |
          mkdir -p dist/linux/amd64/bin
          GOOS=linux GOARCH=amd64 go build -o dist/linux/amd64/bin/hotrod ./cmd/driver

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push driver service image
        run: |
            IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/hotrod-driver:${{ github.head_ref }}
            echo "Building and pushing $IMAGE_NAME"
            docker build \
            --platform linux/amd64 \
            --build-arg TARGETPLATFORM=linux/amd64 \
            --build-arg SERVICE=driver \
            -t $IMAGE_NAME \
            -f Dockerfile .
            docker push $IMAGE_NAME
